id: P010341
initial_creation_type: ocr
source_metadata:
  id: bdr:W20821
  title: བོད་ལྗོངས་སྒྱུ་རྩལ་ཞིབ་འཇུག
  author: ''
  volumes:
    c4c64b7e3a714a4ab3db3375a7c22196:
      image_group_id: I1KG14805
      title: ''
      volume_number: 42
      total_pages: 0
    c3a6f2e4cb744de99e7b2cdb0f50fabe:
      image_group_id: I1KG14806
      title: ''
      volume_number: 43
      total_pages: 126
    64f79ac9fbc6431cb88cf143ee4570e3:
      image_group_id: I1KG14807
      title: ''
      volume_number: 44
      total_pages: 126
    08eea9f98db842049349273af037f87d:
      image_group_id: I1KG14808
      title: ''
      volume_number: 45
      total_pages: 0
    2be4c20e93594f278d00be0cae5e481b:
      image_group_id: I1KG14809
      title: ''
      volume_number: 46
      total_pages: 0
    6560079ce64541f6b0a544c45de99f51:
      image_group_id: I1KG14810
      title: ''
      volume_number: 47
      total_pages: 0
    3b27557efdd24096864ac8bc29060fd3:
      image_group_id: I1KG14811
      title: ''
      volume_number: 48
      total_pages: 0
    6a3a0cde1dda4e7d92055cf2b3775178:
      image_group_id: I1KG14812
      title: ''
      volume_number: 49
      total_pages: 0
    2bca55283f61467fa1c41f5cb2e9c61b:
      image_group_id: I1KG14813
      title: ''
      volume_number: 50
      total_pages: 0
    563d32cdd9f94edda3cb88db7cb0262d:
      image_group_id: I1KG14814
      title: ''
      volume_number: 51
      total_pages: 0
    9a7ad3b76679479ab4243d3b6e36fb65:
      image_group_id: I1PD35620
      title: ''
      volume_number: 1
      total_pages: 140
    bcbafb2d13c8440a858784c96624c04e:
      image_group_id: I1PD35621
      title: ''
      volume_number: 2
      total_pages: 96
    0e7eb2929d28452ea046325cd1d480e6:
      image_group_id: I1PD35622
      title: ''
      volume_number: 3
      total_pages: 122
    d50c53424842496d86c0ec088247024d:
      image_group_id: I1PD35623
      title: ''
      volume_number: 4
      total_pages: 138
    373dfa9359834a5eae6401b6ca62d9e2:
      image_group_id: I1PD35624
      title: ''
      volume_number: 5
      total_pages: 156
    6a2b8f0b44534ca3a0b0e2f1819a7a68:
      image_group_id: I1PD35625
      title: ''
      volume_number: 6
      total_pages: 194
    ac3e18cdfae149d9bd58aa89927f3908:
      image_group_id: I1PD35626
      title: ''
      volume_number: 7
      total_pages: 130
    1e2646e685b54d94ae969f7375ba3f87:
      image_group_id: I1PD35627
      title: ''
      volume_number: 8
      total_pages: 140
    2258417173c44d5e801d9f4cdc373306:
      image_group_id: I1PD35628
      title: ''
      volume_number: 9
      total_pages: 110
    c66a2fd2be7941b6bcc557d3224af10a:
      image_group_id: I1PD35629
      title: ''
      volume_number: 10
      total_pages: 110
    cdec22ba678a4a66879f269bf801ced1:
      image_group_id: I1PD35630
      title: ''
      volume_number: 11
      total_pages: 150
    b6e11223f8bd4f108945d73e05f8f988:
      image_group_id: I1PD35631
      title: ''
      volume_number: 12
      total_pages: 118
    1a5081aad49e4fe5999c13b6e5ec71d8:
      image_group_id: I1PD35632
      title: ''
      volume_number: 13
      total_pages: 134
    d7734c60288546ef89e39b98e38ff514:
      image_group_id: I1PD35633
      title: ''
      volume_number: 14
      total_pages: 136
    e7e542b6f26749a0a144abc576a9276c:
      image_group_id: I1PD35634
      title: ''
      volume_number: 15
      total_pages: 126
    25c662304ac145adbf8cfb78f8fd004a:
      image_group_id: I1PD35635
      title: ''
      volume_number: 16
      total_pages: 142
    a8c3d96e82594a6a97d679343346a6b1:
      image_group_id: I1PD35636
      title: ''
      volume_number: 17
      total_pages: 136
    6ecbe53b46864d6494fbd891fa014626:
      image_group_id: I1PD35637
      title: ''
      volume_number: 18
      total_pages: 0
    956dac03e8224fd6b4c63970ae78eb48:
      image_group_id: I1PD35638
      title: ''
      volume_number: 19
      total_pages: 136
    b1b94d97e0a64468a110c0dcc5ef55fd:
      image_group_id: I1PD35639
      title: ''
      volume_number: 20
      total_pages: 150
    de35c1e6cd7b4b6bbb7450aa03b5df9c:
      image_group_id: I1PD35640
      title: ''
      volume_number: 21
      total_pages: 130
    60357872f6ba4f278d0e4b481f72142f:
      image_group_id: I1PD35641
      title: ''
      volume_number: 22
      total_pages: 146
    3834cae012ac43958bcfb9c128b056ad:
      image_group_id: I1PD35642
      title: ''
      volume_number: 23
      total_pages: 136
    3a226e4e3e064ef4b140fae12487ef7c:
      image_group_id: I1PD35643
      title: ''
      volume_number: 24
      total_pages: 134
    947bbb6d8e514abb80973e68736d9bb8:
      image_group_id: I1PD35644
      title: ''
      volume_number: 25
      total_pages: 142
    a599cdc1ba384e60a4cb6fb9edf64590:
      image_group_id: I1PD35645
      title: ''
      volume_number: 26
      total_pages: 118
    deb03c40b1b74968ae4305b92ed2f535:
      image_group_id: I1PD35646
      title: ''
      volume_number: 27
      total_pages: 114
    a7f25cef7bd148218c5d17b3c45ce4b9:
      image_group_id: I1PD35647
      title: ''
      volume_number: 28
      total_pages: 140
    b6756cda2e4c495eb112a6e047c436c2:
      image_group_id: I1PD35648
      title: ''
      volume_number: 29
      total_pages: 134
    7f9402f9f363414ea811ee61b3c6420d:
      image_group_id: I1PD35649
      title: ''
      volume_number: 30
      total_pages: 126
    a7207702cbfc415fb286e9579da0b505:
      image_group_id: I1PD35650
      title: ''
      volume_number: 31
      total_pages: 148
    25845d5ba718469ca78a24b7eaad5ce6:
      image_group_id: I1PD35651
      title: ''
      volume_number: 32
      total_pages: 150
    f9420cf335424fa0879adb774e713383:
      image_group_id: I1PD35652
      title: ''
      volume_number: 33
      total_pages: 0
    5c54925342ae49a4a0e814f626daa048:
      image_group_id: I1PD35653
      title: ''
      volume_number: 34
      total_pages: 0
    a408cb4c6780408cabb65bbe2eff835d:
      image_group_id: I1PD35654
      title: ''
      volume_number: 35
      total_pages: 0
    e0e9282cca544fadbd27e4c94dd7aea0:
      image_group_id: I1PD35655
      title: ''
      volume_number: 36
      total_pages: 0
    5e58b9425586457f93ca41299baad446:
      image_group_id: I1PD35656
      title: ''
      volume_number: 37
      total_pages: 0
    f1c979740d3f47b98ae2fdd25de3e5e9:
      image_group_id: I1PD35657
      title: ''
      volume_number: 38
      total_pages: 0
    e85e7c05685744c59893cf89a755d63f:
      image_group_id: I1PD35658
      title: ''
      volume_number: 39
      total_pages: 0
    0a9c603d2ee94e8c84df90eacd0c3768:
      image_group_id: I1PD35659
      title: ''
      volume_number: 40
      total_pages: 0
    4f3cb1e3a284495c92543ce2cb84b193:
      image_group_id: I1PD35660
      title: ''
      volume_number: 41
      total_pages: 0
