id: IB1D4D8F1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T21:35:54+00:00'
last_modified: '2022-06-08T12:52:54.497374+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20821
  title: བོད་ལྗོངས་སྒྱུ་རྩལ་ཞིབ་འཇུག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    56D2:
      image_group_id: I1PD35620
      title: ''
      total_pages: 140
      order: 1
      base_file: 56D2.txt
    91FF:
      image_group_id: I1PD35621
      title: ''
      total_pages: 96
      order: 2
      base_file: 91FF.txt
    CCC5:
      image_group_id: I1PD35622
      title: ''
      total_pages: 122
      order: 3
      base_file: CCC5.txt
    E954:
      image_group_id: I1PD35623
      title: ''
      total_pages: 138
      order: 4
      base_file: E954.txt
    '8089':
      image_group_id: I1PD35624
      title: ''
      total_pages: 156
      order: 5
      base_file: 8089.txt
    4D52:
      image_group_id: I1PD35625
      title: ''
      total_pages: 194
      order: 6
      base_file: 4D52.txt
    '7044':
      image_group_id: I1PD35626
      title: ''
      total_pages: 130
      order: 7
      base_file: 7044.txt
    109F:
      image_group_id: I1PD35627
      title: ''
      total_pages: 140
      order: 8
      base_file: 109F.txt
    FB56:
      image_group_id: I1PD35628
      title: ''
      total_pages: 110
      order: 9
      base_file: FB56.txt
    AB45:
      image_group_id: I1PD35629
      title: ''
      total_pages: 110
      order: 10
      base_file: AB45.txt
    E151:
      image_group_id: I1PD35630
      title: ''
      total_pages: 150
      order: 11
      base_file: E151.txt
    '4704':
      image_group_id: I1PD35631
      title: ''
      total_pages: 118
      order: 12
      base_file: 4704.txt
    155C:
      image_group_id: I1PD35632
      title: ''
      total_pages: 134
      order: 13
      base_file: 155C.txt
    F4B1:
      image_group_id: I1PD35633
      title: ''
      total_pages: 136
      order: 14
      base_file: F4B1.txt
    0925:
      image_group_id: I1PD35634
      title: ''
      total_pages: 126
      order: 15
      base_file: 0925.txt
    74C7:
      image_group_id: I1PD35635
      title: ''
      total_pages: 142
      order: 16
      base_file: 74C7.txt
    EE8B:
      image_group_id: I1PD35636
      title: ''
      total_pages: 136
      order: 17
      base_file: EE8B.txt
    D1DC:
      image_group_id: I1PD35637
      title: ''
      total_pages: 0
      order: 18
      base_file: D1DC.txt
    '6087':
      image_group_id: I1PD35638
      title: ''
      total_pages: 136
      order: 19
      base_file: 6087.txt
    8FD3:
      image_group_id: I1PD35639
      title: ''
      total_pages: 150
      order: 20
      base_file: 8FD3.txt
    652E:
      image_group_id: I1PD35640
      title: ''
      total_pages: 130
      order: 21
      base_file: 652E.txt
    '4044':
      image_group_id: I1PD35641
      title: ''
      total_pages: 146
      order: 22
      base_file: 4044.txt
    4C6C:
      image_group_id: I1PD35642
      title: ''
      total_pages: 136
      order: 23
      base_file: 4C6C.txt
    F126:
      image_group_id: I1PD35643
      title: ''
      total_pages: 134
      order: 24
      base_file: F126.txt
    '3314':
      image_group_id: I1PD35644
      title: ''
      total_pages: 142
      order: 25
      base_file: 3314.txt
    2B8F:
      image_group_id: I1PD35645
      title: ''
      total_pages: 118
      order: 26
      base_file: 2B8F.txt
    C607:
      image_group_id: I1PD35646
      title: ''
      total_pages: 114
      order: 27
      base_file: C607.txt
    '5088':
      image_group_id: I1PD35647
      title: ''
      total_pages: 140
      order: 28
      base_file: 5088.txt
    6D24:
      image_group_id: I1PD35648
      title: ''
      total_pages: 134
      order: 29
      base_file: 6D24.txt
    9B19:
      image_group_id: I1PD35649
      title: ''
      total_pages: 126
      order: 30
      base_file: 9B19.txt
    '6854':
      image_group_id: I1PD35650
      title: ''
      total_pages: 148
      order: 31
      base_file: 6854.txt
    EFE5:
      image_group_id: I1PD35651
      title: ''
      total_pages: 150
      order: 32
      base_file: EFE5.txt
    A717:
      image_group_id: I1PD35652
      title: ''
      total_pages: 0
      order: 33
      base_file: A717.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
